### PR TITLE
Added a few more test's and ignore pug files in node_modul folder

### PR DESCRIPTION
**Pull request by pure180**
Using the root `directory = '.'` ensures to resolve all files, even in in the `./node_modules` folder. This does not make sense, especially using the file extension `*.pug`. In this case all tests and later compiles will fail, because of error test files from dependent pug-packages which use the ".pug" extension. For example: `./node_modules/pug-lexer/test/errors/*.pug`

Resolved this by adding a ignore list to package.json and iterate through the new object to compare it with the full filepath.

### CODE REVIEW

**Comment by adammockor** [comment]
Isn't better to pass `skipInheritances` by `options` instead of as `package.json` config?

**Comment by pure180** [comment]
I guess you are right, putting it in a global scope would be better. But we also should prevent users which use their root directoies, to resolve the node-modules folder? 

I am also not a friend of hard coded configuration strings in main application files do you have a suggestion?

**Comment by adammockor** [comment]
You can probably leave skipInheritances in package.json with default options (node-modules, ?bower_components), but this defaults should by overwritable from options object.

**Comment by pure180** [comment]
This will be the way we do it, guess thats the best solution.
Ill take care of it, later in my break. My boss dont likes it, when i do opensource stuff during the work... Even when i use it over here, stupid dumphead... haha

**Comment by adammockor** [comment]
Nice, thank you :)

**Comment by pure180** [comment]
Added skip inheritances option to global options object, can you please take a look on it? Thanks!

**Comment by adammockor** [comment]
Looks good to me, but can you resolve merge conflicts? Then I will merge this publish new version.

**Comment by pure180** [comment]
merge conflicts resolved, ready to go! thanks :-)

**Comment by adammockor** [comment]
Merged and published as 1.1.0

**Comment by pure180** [comment]
Great, thank you. Allredy tested it in the modified gulp-jade-inheritance plugin, works like a charm. We may think about to make this plugin as an alone standing Version instead.  May you talk with Paul Young about that? I guess it's better because issues can take place in the updated Version.

**Pull request merged**
