### PR TITLE
Add dynamic file extension to options

### PR DESCRIPTION
**Pull request by pure180**
Add dynamic file extension to global options. For developers, which
already use the file extension ".pug" instead of ".jade".

I dont know why, but test 4 is throwing an error... also if I use a fresh clone of your repo, just with a modified test file (added escaped backslash "\") to run the test on a windows pc.

Exept this all is working fine.

### CODE REVIEW

**Comment by adammockor** [comment]
Thank you, I will check it out ASAP.

**Comment by adammockor** [comment]
Please can you merge my master here? 

I removed 4th test, because it was badly designed (lib parses all files every-time so error should be thrown in every test in case of syntax error etc.)

Also I tried to update the test file to run on Windows too. Please can you check it?

And please could you write test case for different extensions?

Thank you!

**Comment by pure180** [comment]
Thanks fo your quick response.

Your new test is running great on a windows pc.
Ill update my forked version first and of course i can write a test for the different extensions. ill create a new pullrequest then.

But i guess iam not able to merge it into your master then.

**Comment by pure180** [comment]
Can you please create a new branch in which we can merge my changes first, before publishing my pull requests? For now, all is working fine.

There is still some work todo:
1. Using the root `directory = '.'` ensures to resolve all files, even in in the `./node_modules` folder. This does not make sense, especially using the file extension ".pug". In this case all tests and later compiles will fail, because of error test files from dependent pug-packages which use the ".pug" extension. For example: `./node_modules/pug-lexer/test/errors/*.pug`
   My conclusion, we need to find a way to ignore files inside known packagefolders.
2. We should update the extension to support pug-blocks. `RawInclude` for example is deprecated, we should use ´include´ instead, even resolving template blocks musst be supported.

**Comment by adammockor** [comment]
Ok, I created dev branch and merged your master into.

**Comment by pure180** [comment]
Thanks, I'll take of it tomorrow. May you give me write access to the new Branch.

**Comment by adammockor** [comment]
I made you a collaborator, you should have access now.

**Comment by pure180** [comment]
Thanks, I received your invitation. I'll continue to work on my fork and pull only finished versions.

**Pull request merged**
