### PR TITLE
Use new pug-walk syntax with fallback to deprecated JADE / PUG versions

### PR DESCRIPTION
**Pull request by pure180**
Added a `JADE / PUG` version control module to check the current used `JADE / PUG` version.
Init this module in the main file and assign a boolean variable to the global options object as `options.deprecated`.
Use new pug-walk syntax with fallback for deprecated jade versions. Check for
`Include` if version is newer then `1.11.1`, use `RawInclude` if version is
`1.11.0` or older.

TODO:
description in readme.md

@adammockor can you please take a look on it, thanks?

### CODE REVIEW

**Comment by adammockor** [comment]
I am okey with this right now, because it solves issues, but when pug goes stable and be more adapted in community, we should probably stop supporting both jade and pug, right?

**Comment by pure180** [comment]
Yes, you are right. For the moment I am using many build environments with the deprecated jade version. But my new project's didn't worked with this plugin, would be nice to solve this issues.

Later we can remove this parts then. 

Can you release a preversion of it first, so that I can test it my Apps. To ensure that everything is working as expected?

**Comment by adammockor** [comment]
If you want to test it out you can put this to your `package.json` and it will use your current master branch 

```
{
  "devDependencies": {
    "pug-inheritance": "pure180/pug-inheritance",
  }
}
```

**Comment by pure180** [comment]
I tested in in a few build enviroments and it seems to work fine with regular jade syntax. I will change the default depreacated version from 1.11.0 to 1.10.0, because the 1.11 allready works with the new pulkwalk syntax.

**Comment by adammockor** [comment]
Good.

Have you any idea how to test this? :D

If not I will merge this and publish new version.

**Comment by pure180** [comment]
Yes, I do. In fact that it is already tested of the existing tests. But I'll write an own one for the new version module, later. I'll advise you when done. :-)

**Comment by pure180** [comment]
Sorry for the delay, didn't had much time last days. 
Made a few changes and added a new test to check the new version module. If you are fine with this, you can give it a go. :-)

**Comment by adammockor** [comment]
Merged an published as 1.2.0. Thank you for your effort! 💯

**Pull request merged**
